### PR TITLE
WIP: Refs #adding devise login forms

### PR DESCRIPTION
**Pull request by sarathyerra14**

### CODE REVIEW

**Comment by ghraka** [comment]
@giridhar : Do we need registration and confirmation of user accounts in our application?

**Comment by giridhar** [comment]
registration and confirmation in not needed.

**Comment by ghraka** [comment]
@sarathyerra14: Can you remove those views ?

**Comment by sarathpyerra** [comment]
Sure @giridhar &  @ghraka i will remove registration & confirmation.i am still adding some changes this PR is not ready Yet for review FYI.

**Pull request merged**
